### ISSUE TITLE
The module don't work on lineageOS 21

### ISSUE THREAD

**Issue by enese94** [reiryuki/Sound-Enhancement-Sony-Xperia-10-Magisk-Module#5]
On The Xperia 1ii with lineageOS 20 this module worked flawlessly, but with the lineage OS 21 the module stopped working. New versions don't even open the app (it crashes immediately) older versions from 2023 the app opens but crashes after press on the toggles. The Dolby app opens, but doesn't permit to activate the Dolby audio.

**Comment by reiryuki** [comment]
I will never support 'talking only' without sending proper logs. If you want a fix, then read #bug_report carefully, and send required files to the author.
